/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddEventDto { 
    title?: string | null;
    description?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    addressCity?: string | null;
    addressBuildingNumber?: string | null;
    addressPostalCode?: string | null;
    addressStreet?: string | null;
}

