/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    guid?: string | null;
    street?: string | null;
    city?: string | null;
    region?: string | null;
    buildingNumber?: string | null;
    flatNumber?: string | null;
    postalCode: string | null;
}

