/**
 * KeycloakApiTemplate | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthInfo { 
    isAuthenticated: boolean;
    guid: string;
    roles: Array<string>;
    claims: Array<string>;
    name: string;
    surname: string;
    email: string;
}

