/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Event { 
    guid?: string;
    organizationGuid?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    addressGuid?: string | null;
    qualifications?: string | null;
    closed?: boolean;
}

