/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantDto } from './participantDto';


export interface EventDto { 
    guid?: string;
    organizationGuid?: string | null;
    organizationName?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    addressGuid?: string | null;
    addressCity?: string | null;
    addressStreet?: string | null;
    qualifications?: string | null;
    closed?: boolean;
    participants?: Array<ParticipantDto> | null;
}

