/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantEventStatus } from './participantEventStatus';


export interface PatchUserStatusEventDto { 
    eventId?: string;
    userId?: string;
    participantEventStatus?: ParticipantEventStatus;
}



