/**
 * KeycloakApiTemplate
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentDto { 
    guid?: string;
    name?: string | null;
    surname?: string | null;
    email?: string | null;
    phone?: string | null;
    schoolGuid?: string;
}

